let prototype =
  lazy ([| 
       (*    01234567890123456789*) 
       (*0*)"HHHHHHHHHHHHHHHHHHHH";
       (*1*)"HHHHHHHHHHHHHHHHHHHH";
       (*2*)"HHHHHHHHHHHHHHHHHHHH";
       (*3*)"HHHHHHHHHHHHHHHHHHHH";
       (*4*)"HHHHHHHHHHHHHHHHHHHH";
       (*5*)"HHHHHHHHHHHHHHHHHHHH";
       (*6*)"HHHHHHHHHHHHHHHHHHHH";
       (*7*)"HHHHHHHHHHHHHHHHHHHH";
       (*8*)"HHHHHHHHHHHHHHHHHHHH";
       (*9*)"HHHHHHHHHHHHHHHHHHHH";
       (*0*)"HHHHHHHHHHHHHHHHHHHH";
       (*1*)"HHHHHHHHHHHHHHHHHHHH";
       (*2*)"HHHHHHHHHHHHHHHHHHHH";
       (*3*)"HHHHHHHHHHHHHHHHHHHH";
       (*4*)"HHHHHHHHHHHHHHHHHHHH";
       (*5*)"HHHHHHHHHHHHHHHHHHHH";
       (*6*)"HHHHHHHHHHHHHHHHHHHH";
       (*7*)"HHHHHHHHHHHHHHHHHHHH";
       (*8*)"HHHHHHHHHHHHHHHHHHHH";
       (*9*)"HHHHHHHHHHHHHHHHHHHH";
       |])
