(* This file was auto generated by lvlgen *)

let flora  = [ "0";
               " ";
               " ";
               " ";
               " "
	     ]
let fauna  = [ " ";
               " ";
               " ";
               " ";
               "a"
	     ]
let active = [ " ";
               " ";
               " ";
               " ";
               "X"
	     ]
