(* This file was auto generated by lvlgen *)
module O = struct
  module O = struct
    module O = O_O_O
    module OO = O_O_OO
    module OOO = O_O_OOO
    module OOOO = O_O_OOOO
    module OOOOO = O_O_OOOOO
    module OOOOOO = O_O_OOOOOO
  end

  module OO = struct
    module O = O_OO_O
    module OO = O_OO_OO
    module OOO = O_OO_OOO
    module OOOO = O_OO_OOOO
    module OOOOO = O_OO_OOOOO
    module OOOOOO = O_OO_OOOOOO
  end

  module OOO = struct
    module O = O_OOO_O
    module OO = O_OOO_OO
    module OOO = O_OOO_OOO
    module OOOO = O_OOO_OOOO
    module OOOOO = O_OOO_OOOOO
    module OOOOOO = O_OOO_OOOOOO
  end

  module OOOO = struct
    module O = O_OOOO_O
    module OO = O_OOOO_OO
    module OOO = O_OOOO_OOO
    module OOOO = O_OOOO_OOOO
    module OOOOO = O_OOOO_OOOOO
    module OOOOOO = O_OOOO_OOOOOO
  end

  module OOOOO = struct
    module O = O_OOOOO_O
    module OO = O_OOOOO_OO
    module OOO = O_OOOOO_OOO
    module OOOO = O_OOOOO_OOOO
    module OOOOO = O_OOOOO_OOOOO
    module OOOOOO = O_OOOOO_OOOOOO
  end

  module OOOOOO = struct
    module O = O_OOOOOO_O
    module OO = O_OOOOOO_OO
    module OOO = O_OOOOOO_OOO
    module OOOO = O_OOOOOO_OOOO
    module OOOOO = O_OOOOOO_OOOOO
    module OOOOOO = O_OOOOOO_OOOOOO
  end

end

module OO = struct
  module O = struct
    module O = OO_O_O
    module OO = OO_O_OO
    module OOO = OO_O_OOO
    module OOOO = OO_O_OOOO
    module OOOOO = OO_O_OOOOO
    module OOOOOO = OO_O_OOOOOO
  end

  module OO = struct
    module O = OO_OO_O
    module OO = OO_OO_OO
    module OOO = OO_OO_OOO
    module OOOO = OO_OO_OOOO
    module OOOOO = OO_OO_OOOOO
    module OOOOOO = OO_OO_OOOOOO
  end

  module OOO = struct
    module O = OO_OOO_O
    module OO = OO_OOO_OO
    module OOO = OO_OOO_OOO
    module OOOO = OO_OOO_OOOO
    module OOOOO = OO_OOO_OOOOO
    module OOOOOO = OO_OOO_OOOOOO
  end

  module OOOO = struct
    module O = OO_OOOO_O
    module OO = OO_OOOO_OO
    module OOO = OO_OOOO_OOO
    module OOOO = OO_OOOO_OOOO
    module OOOOO = OO_OOOO_OOOOO
    module OOOOOO = OO_OOOO_OOOOOO
  end

  module OOOOO = struct
    module O = OO_OOOOO_O
    module OO = OO_OOOOO_OO
    module OOO = OO_OOOOO_OOO
    module OOOO = OO_OOOOO_OOOO
    module OOOOO = OO_OOOOO_OOOOO
    module OOOOOO = OO_OOOOO_OOOOOO
  end

  module OOOOOO = struct
    module O = OO_OOOOOO_O
    module OO = OO_OOOOOO_OO
    module OOO = OO_OOOOOO_OOO
    module OOOO = OO_OOOOOO_OOOO
    module OOOOO = OO_OOOOOO_OOOOO
    module OOOOOO = OO_OOOOOO_OOOOOO
  end

end

module OOO = struct
  module O = struct
    module O = OOO_O_O
    module OO = OOO_O_OO
    module OOO = OOO_O_OOO
    module OOOO = OOO_O_OOOO
    module OOOOO = OOO_O_OOOOO
    module OOOOOO = OOO_O_OOOOOO
  end

  module OO = struct
    module O = OOO_OO_O
    module OO = OOO_OO_OO
    module OOO = OOO_OO_OOO
    module OOOO = OOO_OO_OOOO
    module OOOOO = OOO_OO_OOOOO
    module OOOOOO = OOO_OO_OOOOOO
  end

  module OOO = struct
    module O = OOO_OOO_O
    module OO = OOO_OOO_OO
    module OOO = OOO_OOO_OOO
    module OOOO = OOO_OOO_OOOO
    module OOOOO = OOO_OOO_OOOOO
    module OOOOOO = OOO_OOO_OOOOOO
  end

  module OOOO = struct
    module O = OOO_OOOO_O
    module OO = OOO_OOOO_OO
    module OOO = OOO_OOOO_OOO
    module OOOO = OOO_OOOO_OOOO
    module OOOOO = OOO_OOOO_OOOOO
    module OOOOOO = OOO_OOOO_OOOOOO
  end

  module OOOOO = struct
    module O = OOO_OOOOO_O
    module OO = OOO_OOOOO_OO
    module OOO = OOO_OOOOO_OOO
    module OOOO = OOO_OOOOO_OOOO
    module OOOOO = OOO_OOOOO_OOOOO
    module OOOOOO = OOO_OOOOO_OOOOOO
  end

  module OOOOOO = struct
    module O = OOO_OOOOOO_O
    module OO = OOO_OOOOOO_OO
    module OOO = OOO_OOOOOO_OOO
    module OOOO = OOO_OOOOOO_OOOO
    module OOOOO = OOO_OOOOOO_OOOOO
    module OOOOOO = OOO_OOOOOO_OOOOOO
  end

end

module OOOO = struct
  module O = struct
    module O = OOOO_O_O
    module OO = OOOO_O_OO
    module OOO = OOOO_O_OOO
    module OOOO = OOOO_O_OOOO
    module OOOOO = OOOO_O_OOOOO
    module OOOOOO = OOOO_O_OOOOOO
  end

  module OO = struct
    module O = OOOO_OO_O
    module OO = OOOO_OO_OO
    module OOO = OOOO_OO_OOO
    module OOOO = OOOO_OO_OOOO
    module OOOOO = OOOO_OO_OOOOO
    module OOOOOO = OOOO_OO_OOOOOO
  end

  module OOO = struct
    module O = OOOO_OOO_O
    module OO = OOOO_OOO_OO
    module OOO = OOOO_OOO_OOO
    module OOOO = OOOO_OOO_OOOO
    module OOOOO = OOOO_OOO_OOOOO
    module OOOOOO = OOOO_OOO_OOOOOO
  end

  module OOOO = struct
    module O = OOOO_OOOO_O
    module OO = OOOO_OOOO_OO
    module OOO = OOOO_OOOO_OOO
    module OOOO = OOOO_OOOO_OOOO
    module OOOOO = OOOO_OOOO_OOOOO
    module OOOOOO = OOOO_OOOO_OOOOOO
  end

  module OOOOO = struct
    module O = OOOO_OOOOO_O
    module OO = OOOO_OOOOO_OO
    module OOO = OOOO_OOOOO_OOO
    module OOOO = OOOO_OOOOO_OOOO
    module OOOOO = OOOO_OOOOO_OOOOO
    module OOOOOO = OOOO_OOOOO_OOOOOO
  end

  module OOOOOO = struct
    module O = OOOO_OOOOOO_O
    module OO = OOOO_OOOOOO_OO
    module OOO = OOOO_OOOOOO_OOO
    module OOOO = OOOO_OOOOOO_OOOO
    module OOOOO = OOOO_OOOOOO_OOOOO
    module OOOOOO = OOOO_OOOOOO_OOOOOO
  end

end

module OOOOO = struct
  module O = struct
    module O = OOOOO_O_O
    module OO = OOOOO_O_OO
    module OOO = OOOOO_O_OOO
    module OOOO = OOOOO_O_OOOO
    module OOOOO = OOOOO_O_OOOOO
    module OOOOOO = OOOOO_O_OOOOOO
  end

  module OO = struct
    module O = OOOOO_OO_O
    module OO = OOOOO_OO_OO
    module OOO = OOOOO_OO_OOO
    module OOOO = OOOOO_OO_OOOO
    module OOOOO = OOOOO_OO_OOOOO
    module OOOOOO = OOOOO_OO_OOOOOO
  end

  module OOO = struct
    module O = OOOOO_OOO_O
    module OO = OOOOO_OOO_OO
    module OOO = OOOOO_OOO_OOO
    module OOOO = OOOOO_OOO_OOOO
    module OOOOO = OOOOO_OOO_OOOOO
    module OOOOOO = OOOOO_OOO_OOOOOO
  end

  module OOOO = struct
    module O = OOOOO_OOOO_O
    module OO = OOOOO_OOOO_OO
    module OOO = OOOOO_OOOO_OOO
    module OOOO = OOOOO_OOOO_OOOO
    module OOOOO = OOOOO_OOOO_OOOOO
    module OOOOOO = OOOOO_OOOO_OOOOOO
  end

  module OOOOO = struct
    module O = OOOOO_OOOOO_O
    module OO = OOOOO_OOOOO_OO
    module OOO = OOOOO_OOOOO_OOO
    module OOOO = OOOOO_OOOOO_OOOO
    module OOOOO = OOOOO_OOOOO_OOOOO
    module OOOOOO = OOOOO_OOOOO_OOOOOO
  end

  module OOOOOO = struct
    module O = OOOOO_OOOOOO_O
    module OO = OOOOO_OOOOOO_OO
    module OOO = OOOOO_OOOOOO_OOO
    module OOOO = OOOOO_OOOOOO_OOOO
    module OOOOO = OOOOO_OOOOOO_OOOOO
    module OOOOOO = OOOOO_OOOOOO_OOOOOO
  end

end

module OOOOOO = struct
  module O = struct
    module O = OOOOOO_O_O
    module OO = OOOOOO_O_OO
    module OOO = OOOOOO_O_OOO
    module OOOO = OOOOOO_O_OOOO
    module OOOOO = OOOOOO_O_OOOOO
    module OOOOOO = OOOOOO_O_OOOOOO
  end

  module OO = struct
    module O = OOOOOO_OO_O
    module OO = OOOOOO_OO_OO
    module OOO = OOOOOO_OO_OOO
    module OOOO = OOOOOO_OO_OOOO
    module OOOOO = OOOOOO_OO_OOOOO
    module OOOOOO = OOOOOO_OO_OOOOOO
  end

  module OOO = struct
    module O = OOOOOO_OOO_O
    module OO = OOOOOO_OOO_OO
    module OOO = OOOOOO_OOO_OOO
    module OOOO = OOOOOO_OOO_OOOO
    module OOOOO = OOOOOO_OOO_OOOOO
    module OOOOOO = OOOOOO_OOO_OOOOOO
  end

  module OOOO = struct
    module O = OOOOOO_OOOO_O
    module OO = OOOOOO_OOOO_OO
    module OOO = OOOOOO_OOOO_OOO
    module OOOO = OOOOOO_OOOO_OOOO
    module OOOOO = OOOOOO_OOOO_OOOOO
    module OOOOOO = OOOOOO_OOOO_OOOOOO
  end

  module OOOOO = struct
    module O = OOOOOO_OOOOO_O
    module OO = OOOOOO_OOOOO_OO
    module OOO = OOOOOO_OOOOO_OOO
    module OOOO = OOOOOO_OOOOO_OOOO
    module OOOOO = OOOOOO_OOOOO_OOOOO
    module OOOOOO = OOOOOO_OOOOO_OOOOOO
  end

  module OOOOOO = struct
    module O = OOOOOO_OOOOOO_O
    module OO = OOOOOO_OOOOOO_OO
    module OOO = OOOOOO_OOOOOO_OOO
    module OOOO = OOOOOO_OOOOOO_OOOO
    module OOOOO = OOOOOO_OOOOOO_OOOOO
    module OOOOOO = OOOOOO_OOOOOO_OOOOOO
  end

end

